### ISSUE TITLE
Version 1.16 is not supported

### ISSUE THREAD

**Issue by BlockCityNetwork** [CloudburstMC/Nemisys#70]
I noticed that there was an update of Nemisys on July 3rd,but it still doesn't support version 1.16.Many servers have been upgraded to version 1.16,so please let Nemisys support version 1.16 as soon as possible.

**Comment by tuilakhanh** [comment]
This version is not recommended for use

Try petterim1 version

https://github.com/PetteriM1/NemisysProxy

**Comment by BlockCityNetwork** [comment]
> This version is not recommended for use
> 
> Try petterim1 version
> 
> https://github.com/PetteriM1/NemisysProxy

Actually, I've already used it,but CustomSynapseAPI For NukkitX does not seem to support NukkitX version 1.16,It has some unknown errors.

**Comment by tuilakhanh** [comment]
> > This version is not recommended for use
> > 
> > Try petterim1 version
> > 
> > https://github.com/PetteriM1/NemisysProxy
> 
> Actually, I've already used it,but CustomSynapseAPI For NukkitX does not seem to support NukkitX version 1.16,It has some unknown errors.

What is the error ? 

Another way is use waterdog

**Comment by PigeonNeverCoo** [comment]
> > > 不建议使用此版本
> > > 尝试 petterim1 版本
> > > https://github.com/PetteriM1/NemisysProxy
> > 
> > 
> > 实际上，我已经用过它，但NukkitX的自定义SynapseAPI似乎不支持NukkitX版本1.16，它有一些未知的错误。
> 
> 错误是什么？
> 
> 另一种方式是使用水狗

[logs.txt](https://github.com/CloudburstMC/Nemisys/files/4924575/logs.txt)
Here is logs.
(The Nukkit plugin can't execute the Waterdog command,)

**Comment by tuilakhanh** [comment]
@PigeonNeverCoo did you run lastest version of synapse and nemisys?

Petteri's nemisys work normaly on my server 

![image](https://user-images.githubusercontent.com/17153084/87540565-1c607b80-c6ca-11ea-9ed7-8f8d3785788c.png)

**Comment by tuilakhanh** [comment]
@PigeonNeverCoo use waterdog tool if you want run waterdog transfer command from nukkit server 

https://github.com/yesdog/WaterdogTools

**Comment by PigeonNeverCoo** [comment]
> @PigeonNeverCoo从 nukkit 服务器运行水狗传输命令， 可以使用水狗工具
> 
> https://github.com/yesdog/WaterdogTools

OK,thank u very much.

**Comment by tuilakhanh** [comment]
> > @PigeonNeverCoo从 nukkit 服务器运行水狗传输命令， 可以使用水狗工具
> > 
> > https://github.com/yesdog/WaterdogTools
> 
> OK,thank u very much.

Waterdog 1.16 if u need

https://jenkins.mizerak.eu/view/Alemiz-Jobs/job/WaterDog/job/alemiz-zlib/

**Comment by hardsiamang655** [comment]
Installing after deleting Nemsys nukkiti?
